# Site settings
title: RyanJTurner.com
tagline: For my children.
email: blog@ryanjturner.com
description: > # this means to ignore newlines until "baseurl"
  Leadership is the defining challenge and opportunity of our lives. This blog is a repository of everything I have learned about leadership, which is the legacy I want to leave my children.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ryanjturner.com" # the base hostname & protocol for your site
twitter_username: TurnerRyanJ
github_username:  rjturner
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
