# Site settings
title: RyanJTurner.com
tagline: Dedicated to my children.
email: blog@ryanjturner.com
description: > # this means to ignore newlines until "baseurl"
  A blog about leadership capturing everything I want to teach my children.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ryanjturner.com" # the base hostname & protocol for your site
twitter_username: TurnerRyanJ
github_username:  rjturner
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
